CREATE DATABASE IF NOT EXISTS `order_system` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `order_system`;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '관리자 사용자 고유 ID',
  login_id VARCHAR(50) NOT NULL COMMENT '관리자 로그인 ID',
  password_hash VARCHAR(255) NOT NULL COMMENT '비밀번호 해시값',
  name VARCHAR(50) NOT NULL COMMENT '관리자 이름',
  email VARCHAR(120) NULL COMMENT '이메일 주소',
  role ENUM('ADMIN', 'MANAGER', 'STAFF') NOT NULL DEFAULT 'STAFF' COMMENT '관리자 권한: ADMIN 최고관리자, MANAGER 매니저, STAFF 담당자',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_login_id (login_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='본사 관리자 사용자';

CREATE TABLE IF NOT EXISTS stores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '거래처/매장 고유 ID',
  store_uid VARCHAR(50) NOT NULL COMMENT '시스템 내부 거래처 고유키',
  store_code VARCHAR(50) NULL COMMENT '세금계산서 발행/업무용 거래처 코드',
  store_name VARCHAR(120) NOT NULL COMMENT '매장명',
  tax_invoice_code VARCHAR(50) NULL COMMENT '세금계산서 발행코드',
  tax_invoice_name VARCHAR(120) NULL COMMENT '매장명 표시값(기존 세금계산서 발행명 호환 컬럼)',
  machine_vendor VARCHAR(120) NULL COMMENT '머신매입처',
  device_number VARCHAR(120) NULL COMMENT '기기번호',
  owner_name VARCHAR(50) NULL COMMENT '점주/대표자명',
  owner_phone VARCHAR(30) NULL COMMENT '점주/대표자 연락처',
  contact_phone2 VARCHAR(30) NULL COMMENT '추가 연락처',
  business_number VARCHAR(30) NULL COMMENT '사업자등록번호',
  address1 VARCHAR(255) NULL COMMENT '주소1',
  address2 VARCHAR(255) NULL COMMENT '주소2',
  machine_name VARCHAR(120) NULL COMMENT '설치 머신명(표시/호환용)',
  bean_name VARCHAR(120) NULL COMMENT '사용 원두명',
  as_content VARCHAR(255) NULL COMMENT 'A/S 내용',
  closure_status VARCHAR(20) NOT NULL DEFAULT '운영중' COMMENT '영업상태: 운영중, 폐업',
  installed_at DATE NULL COMMENT '설치일자',
  filter_replaced_at DATE NULL COMMENT '필터교체일자',
  payment_type ENUM('PREPAID', 'MONTHLY', 'SPECIAL') NOT NULL DEFAULT 'PREPAID' COMMENT '기본 결제유형: PREPAID 선결제, MONTHLY 월결제, SPECIAL 별도협의',
  memo TEXT NULL COMMENT '거래처/매장 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stores_store_uid (store_uid),
  UNIQUE KEY uq_stores_store_code (store_code),
  KEY idx_stores_store_name (store_name),
  KEY idx_stores_owner_phone (owner_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='거래처/매장 기본 정보';

CREATE TABLE IF NOT EXISTS store_owners (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '점주 계정 고유 ID',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '매장 ID',
  login_id VARCHAR(50) NOT NULL COMMENT '점주 로그인 ID',
  password_hash VARCHAR(255) NOT NULL COMMENT '비밀번호 해시값',
  name VARCHAR(50) NOT NULL COMMENT '점주 이름',
  phone VARCHAR(30) NULL COMMENT '점주 연락처',
  email VARCHAR(120) NULL COMMENT '점주 이메일',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_store_owners_login_id (login_id),
  KEY idx_store_owners_store_id (store_id),
  CONSTRAINT fk_store_owners_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='점주 마이페이지 계정';

CREATE TABLE IF NOT EXISTS store_inquiries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '문의 고유 ID',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '매장 ID',
  store_owner_id BIGINT UNSIGNED NULL COMMENT '점주 계정 ID',
  inquiry_type ENUM('ORDER', 'PAYMENT', 'MACHINE', 'ITEM', 'ETC') NOT NULL DEFAULT 'ETC' COMMENT '문의 유형',
  title VARCHAR(200) NOT NULL COMMENT '문의 제목',
  content TEXT NOT NULL COMMENT '문의 내용',
  status ENUM('OPEN', 'ANSWERED', 'CLOSED') NOT NULL DEFAULT 'OPEN' COMMENT '처리 상태',
  answer TEXT NULL COMMENT '관리자 답변',
  answered_by BIGINT UNSIGNED NULL COMMENT '답변 관리자 ID',
  answered_at DATETIME NULL COMMENT '답변 일시',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '문의 생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_store_inquiries_store_title (store_id, title),
  KEY idx_store_inquiries_store_id (store_id),
  KEY idx_store_inquiries_owner_id (store_owner_id),
  KEY idx_store_inquiries_status (status),
  CONSTRAINT fk_store_inquiries_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_store_inquiries_owner FOREIGN KEY (store_owner_id) REFERENCES store_owners(id),
  CONSTRAINT fk_store_inquiries_answered_by FOREIGN KEY (answered_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='점주 문의내역';

CREATE TABLE IF NOT EXISTS items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '품목 고유 ID',
  item_code VARCHAR(50) NOT NULL COMMENT '품목 코드',
  category_name VARCHAR(100) NULL COMMENT '품목 카테고리명',
  supplier_name VARCHAR(120) NULL COMMENT '제품 업체명',
  name VARCHAR(150) NOT NULL COMMENT '품목명',
  spec VARCHAR(120) NULL COMMENT '규격 정보',
  unit VARCHAR(20) NOT NULL DEFAULT 'EA' COMMENT '단위',
  purchase_price BIGINT NOT NULL DEFAULT 0 COMMENT '입고단가',
  sale_price BIGINT NOT NULL DEFAULT 0 COMMENT '출고단가',
  keywords VARCHAR(255) NULL COMMENT '검색 키워드',
  memo TEXT NULL COMMENT '품목 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_items_item_code (item_code),
  KEY idx_items_name (name),
  KEY idx_items_supplier_name (supplier_name),
  KEY idx_items_category_name (category_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='판매 품목';

CREATE TABLE IF NOT EXISTS machine_catalogs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '머신 카탈로그 고유 ID',
  machine_code VARCHAR(50) NOT NULL COMMENT '머신 코드',
  company_name VARCHAR(120) NULL COMMENT '머신회사명',
  machine_name VARCHAR(120) NOT NULL COMMENT '머신명',
  model_name VARCHAR(120) NULL COMMENT '모델명',
  memo TEXT NULL COMMENT '머신 카탈로그 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_machine_catalogs_code (machine_code),
  KEY idx_machine_catalogs_name (machine_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='머신 기본 카탈로그';

CREATE TABLE IF NOT EXISTS machines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '머신 고유 ID',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '설치 매장 ID',
  machine_catalog_id BIGINT UNSIGNED NULL COMMENT '머신 마스터 ID',
  machine_code VARCHAR(50) NULL COMMENT '머신 코드',
  machine_name VARCHAR(120) NOT NULL COMMENT '머신명',
  model_name VARCHAR(120) NULL COMMENT '모델명',
  serial_number VARCHAR(120) NULL COMMENT '시리얼번호',
  installed_at DATE NULL COMMENT '설치일자',
  memo TEXT NULL COMMENT '머신 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_machines_machine_code (machine_code),
  KEY idx_machines_store_id (store_id),
  KEY idx_machines_catalog_id (machine_catalog_id),
  CONSTRAINT fk_machines_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_machines_catalog FOREIGN KEY (machine_catalog_id) REFERENCES machine_catalogs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매장별 설치 머신';

CREATE TABLE IF NOT EXISTS machine_catalog_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '머신 기본 품목 고유 ID',
  machine_catalog_id BIGINT UNSIGNED NOT NULL COMMENT '머신 카탈로그 ID',
  item_id BIGINT UNSIGNED NOT NULL COMMENT '품목 ID',
  memo TEXT NULL COMMENT '머신 기본 품목 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_machine_catalog_items (machine_catalog_id, item_id),
  KEY idx_machine_catalog_items_item_id (item_id),
  CONSTRAINT fk_machine_catalog_items_catalog FOREIGN KEY (machine_catalog_id) REFERENCES machine_catalogs(id),
  CONSTRAINT fk_machine_catalog_items_item FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='머신 카탈로그별 기본 품목';

CREATE TABLE IF NOT EXISTS store_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '매장별 품목 고유 ID',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '매장 ID',
  item_id BIGINT UNSIGNED NOT NULL COMMENT '품목 ID',
  machine_id BIGINT UNSIGNED NULL COMMENT '연결 머신 ID',
  item_scope_key VARCHAR(80) GENERATED ALWAYS AS (CONCAT(store_id, ':', item_id, ':', COALESCE(machine_id, 0))) STORED COMMENT '매장-품목-머신 범위 중복 방지키',
  store_sale_price BIGINT NULL COMMENT '거래처별 출고단가',
  memo TEXT NULL COMMENT '매장별 품목 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_store_items_store_item_machine (store_id, item_id, machine_id),
  UNIQUE KEY uq_store_items_scope_key (item_scope_key),
  KEY idx_store_items_store_id (store_id),
  KEY idx_store_items_item_id (item_id),
  KEY idx_store_items_machine_id (machine_id),
  CONSTRAINT fk_store_items_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_store_items_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_store_items_machine FOREIGN KEY (machine_id) REFERENCES machines(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매장별 취급 품목';

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문 고유 ID',
  order_no VARCHAR(50) NOT NULL COMMENT '주문번호',
  store_id BIGINT UNSIGNED NOT NULL COMMENT '매장 ID',
  order_date DATE NOT NULL COMMENT '주문 접수일',
  due_date DATE NULL COMMENT '희망 납기일',
  request_channel ENUM('KAKAO', 'PHONE', 'SMS', 'ADMIN', 'SHOP', 'ETC') NOT NULL DEFAULT 'ADMIN' COMMENT '주문 접수 경로: ADMIN 관리자입력, SHOP 사용자페이지, KAKAO 카카오톡, PHONE 전화, SMS 문자, ETC 기타',
  order_status ENUM('DRAFT', 'STATEMENT_READY', 'PAYMENT_REQUESTED', 'PAYMENT_CONFIRMED', 'MANUAL_APPROVED', 'ORDER_IN_PROGRESS', 'SHIPPED', 'COMPLETED', 'CANCELED') NOT NULL DEFAULT 'DRAFT' COMMENT '주문 상태: DRAFT 임시저장, STATEMENT_READY 명세서작성, PAYMENT_REQUESTED 결제요청, PAYMENT_CONFIRMED 결제확인, MANUAL_APPROVED 관리자예외승인, ORDER_IN_PROGRESS 사입/발주진행, SHIPPED 발송완료, COMPLETED 완료, CANCELED 취소',
  payment_status ENUM('UNPAID', 'PARTIAL_PAID', 'PAID', 'MONTHLY_BILLING', 'MANUAL_APPROVED', 'REFUNDED') NOT NULL DEFAULT 'UNPAID' COMMENT '결제 상태: UNPAID 미결제, PARTIAL_PAID 부분입금, PAID 결제완료, MONTHLY_BILLING 월결제, MANUAL_APPROVED 관리자예외처리, REFUNDED 환불',
  payment_type ENUM('PREPAID', 'MONTHLY', 'SPECIAL') NOT NULL DEFAULT 'PREPAID' COMMENT '거래처 기본 결제유형 snapshot',
  supply_amount BIGINT NOT NULL DEFAULT 0 COMMENT '공급가액 합계',
  vat_amount BIGINT NOT NULL DEFAULT 0 COMMENT '부가세 합계',
  total_amount BIGINT NOT NULL DEFAULT 0 COMMENT '총 결제 요청 금액',
  paid_amount BIGINT NOT NULL DEFAULT 0 COMMENT '결제 완료 금액',
  request_memo TEXT NULL COMMENT '점주 주문 요청 내용',
  admin_memo TEXT NULL COMMENT '관리자 내부 메모',
  manual_approved_by BIGINT UNSIGNED NULL COMMENT '관리자 예외 승인자 ID',
  manual_approved_reason VARCHAR(255) NULL COMMENT '관리자 예외 승인 사유',
  manual_approved_at DATETIME NULL COMMENT '관리자 예외 승인일시',
  created_by BIGINT UNSIGNED NULL COMMENT '주문 생성 관리자 ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_order_no (order_no),
  KEY idx_orders_store_id (store_id),
  KEY idx_orders_order_date (order_date),
  KEY idx_orders_order_status (order_status),
  KEY idx_orders_payment_status (payment_status),
  CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_orders_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_orders_manual_approved_by FOREIGN KEY (manual_approved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='점주 주문 및 명세서';

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문 품목 상세 고유 ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '주문 ID',
  store_item_id BIGINT UNSIGNED NULL COMMENT '주문 당시 매장별 품목 ID',
  item_id BIGINT UNSIGNED NULL COMMENT '품목 ID',
  item_code VARCHAR(50) NULL COMMENT '주문 당시 품목 코드',
  item_name VARCHAR(150) NOT NULL COMMENT '주문 당시 품목명',
  spec VARCHAR(120) NULL COMMENT '주문 당시 규격 정보',
  unit VARCHAR(20) NOT NULL DEFAULT 'EA' COMMENT '주문 단위',
  quantity DECIMAL(15,3) NOT NULL COMMENT '주문 수량',
  unit_price BIGINT NOT NULL DEFAULT 0 COMMENT '주문 판매단가',
  supply_amount BIGINT NOT NULL DEFAULT 0 COMMENT '공급가액',
  vat_amount BIGINT NOT NULL DEFAULT 0 COMMENT '부가세액',
  total_amount BIGINT NOT NULL DEFAULT 0 COMMENT '합계 금액',
  memo TEXT NULL COMMENT '주문 품목 메모',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  KEY idx_order_items_order_id (order_id),
  KEY idx_order_items_store_item_id (store_item_id),
  KEY idx_order_items_item_id (item_id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_store_item FOREIGN KEY (store_item_id) REFERENCES store_items(id),
  CONSTRAINT fk_order_items_item FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='주문 품목 상세';

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '결제 이력 고유 ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '주문 ID',
  payment_method ENUM('BANK_TRANSFER', 'CARD', 'CASH', 'MANUAL', 'ETC') NOT NULL DEFAULT 'BANK_TRANSFER' COMMENT '결제수단: BANK_TRANSFER 계좌이체, CARD 카드, CASH 현금, MANUAL 수동처리, ETC 기타',
  payment_status ENUM('PENDING', 'CONFIRMED', 'CANCELED', 'REFUNDED') NOT NULL DEFAULT 'CONFIRMED' COMMENT '결제 이력 상태: PENDING 확인대기, CONFIRMED 확인완료, CANCELED 취소, REFUNDED 환불',
  amount BIGINT NOT NULL COMMENT '결제 금액',
  payer_name VARCHAR(80) NULL COMMENT '입금자명',
  paid_at DATETIME NULL COMMENT '결제 또는 입금일시',
  provider VARCHAR(30) NULL COMMENT '결제 제공사: TOSS 등',
  provider_payment_key VARCHAR(120) NULL COMMENT '외부 결제 승인 키',
  provider_order_id VARCHAR(120) NULL COMMENT '외부 결제 주문번호',
  provider_transaction_id VARCHAR(120) NULL COMMENT '외부 거래 식별자',
  receipt_url VARCHAR(500) NULL COMMENT '영수증 URL',
  raw_payload JSON NULL COMMENT '결제사 원본 응답',
  accounting_status ENUM('UNMATCHED', 'MATCHED', 'EXCLUDED') NOT NULL DEFAULT 'UNMATCHED' COMMENT '회계/입금 매칭 상태',
  deposit_account_id BIGINT UNSIGNED NULL COMMENT '입금 확인 계좌 ID',
  bank_transaction_id BIGINT UNSIGNED NULL COMMENT '매칭된 은행 거래내역 ID',
  reconciled_at DATETIME NULL COMMENT '정산 매칭 일시',
  memo TEXT NULL COMMENT '결제 메모',
  created_by BIGINT UNSIGNED NULL COMMENT '결제 처리 관리자 ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  KEY idx_payments_order_id (order_id),
  KEY idx_payments_paid_at (paid_at),
  UNIQUE KEY uq_payments_provider_payment_key (provider_payment_key),
  KEY idx_payments_provider_order_id (provider_order_id),
  KEY idx_payments_accounting_status (accounting_status),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='주문 결제 이력';

CREATE TABLE IF NOT EXISTS order_status_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문 상태 변경 이력 고유 ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '주문 ID',
  from_status VARCHAR(30) NULL COMMENT '변경 전 주문 상태',
  to_status VARCHAR(30) NOT NULL COMMENT '변경 후 주문 상태',
  memo VARCHAR(255) NULL COMMENT '상태 변경 메모',
  changed_by BIGINT UNSIGNED NULL COMMENT '상태 변경 관리자 ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '상태 변경일시',
  PRIMARY KEY (id),
  KEY idx_order_status_logs_order_id (order_id),
  CONSTRAINT fk_order_status_logs_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_status_logs_changed_by FOREIGN KEY (changed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='주문 상태 변경 이력';

CREATE TABLE IF NOT EXISTS company_bank_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '본사 계좌 고유 ID',
  bank_name VARCHAR(50) NOT NULL COMMENT '은행명',
  account_number VARCHAR(50) NOT NULL COMMENT '계좌번호',
  account_holder VARCHAR(80) NOT NULL COMMENT '예금주',
  account_name VARCHAR(80) NULL COMMENT '계좌 별칭',
  memo TEXT NULL COMMENT '계좌 메모',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부: 1 사용, 0 미사용',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_company_bank_accounts_number (account_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='본사 입금 계좌';

CREATE TABLE IF NOT EXISTS hana_b2b_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '하나은행 거래내역 고유 ID',
  account_number VARCHAR(120) NULL COMMENT '계좌번호',
  transaction_date CHAR(8) NOT NULL COMMENT '거래일자(YYYYMMDD)',
  transaction_time CHAR(6) NULL COMMENT '거래시각(HHMMSS)',
  balance_change_code VARCHAR(20) NULL COMMENT '잔액변동구분코드',
  transaction_amount BIGINT NOT NULL DEFAULT 0 COMMENT '거래금액',
  outline VARCHAR(255) NULL COMMENT '적요',
  branch_name VARCHAR(120) NULL COMMENT '취급점명',
  after_balance BIGINT NOT NULL DEFAULT 0 COMMENT '거래후잔액',
  currency_code VARCHAR(10) NOT NULL DEFAULT 'KRW' COMMENT '통화코드',
  spec_serial_no VARCHAR(50) NULL COMMENT '거래명세 일련번호',
  detail_serial_no VARCHAR(50) NULL COMMENT '거래상세 일련번호',
  raw_json JSON NULL COMMENT '하나은행 원본 응답',
  fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '조회일시',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_hana_b2b_transactions (account_number, transaction_date, transaction_time, transaction_amount, outline, after_balance),
  KEY idx_hana_b2b_transactions_date (transaction_date),
  KEY idx_hana_b2b_transactions_account (account_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='하나은행 B2B 입출금 거래내역';

CREATE TABLE IF NOT EXISTS hana_b2b_balances (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '하나은행 잔액 고유 ID',
  account_number VARCHAR(120) NOT NULL COMMENT '계좌번호',
  current_balance BIGINT NOT NULL DEFAULT 0 COMMENT '현재잔액',
  payable_amount BIGINT NOT NULL DEFAULT 0 COMMENT '지급가능금액',
  uncleared_check_amount BIGINT NOT NULL DEFAULT 0 COMMENT '미결제타점권금액',
  payment_stop_amount BIGINT NOT NULL DEFAULT 0 COMMENT '지급정지금액',
  send_date CHAR(8) NULL COMMENT '전송일자(YYYYMMDD)',
  send_time CHAR(6) NULL COMMENT '전송시각(HHMMSS)',
  raw_json JSON NULL COMMENT '하나은행 원본 응답',
  fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '조회일시',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (id),
  UNIQUE KEY uq_hana_b2b_balances_account (account_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='하나은행 B2B 계좌 잔액';

